site_name: Coherence Operator
nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - User Guide: user-guide.md
    - Samples: samples/README.md
theme: readthedocs
palette:
    primary: red
    accent: red

