{{- if .Values.service }}
  {{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "coherence.fullname" . }}
  annotations:
    # ref: https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/watchers/annotations.go#L21
    dns.alpha.kubernetes.io/internal: "{{ .Release.Name }}.{{ .Values.service.domain }}"
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
  labels:
{{- include "coherence.release_labels" . | indent 4 }}
    component: "web-server-service"
spec:
  type: {{ .Values.service.type }}
    {{- if eq .Values.service.type "LoadBalancer" }}
      {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
      {{- end }}
    {{- end }}
  ports:
    - name: http-port
      protocol: TCP
      port: {{ .Values.service.externalPort | default 8080 }}
      targetPort: "http-port"
  selector:
    coherenceDeployment: {{ template "coherence.fullname" . }}
    component: WebServerPod
  {{- end }}
{{- end }}
