apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "coherence.fullname" . }}
  labels:
    {{- include "coherence.release_labels" . | indent 4 }}
    component: coherence
spec:
  replicas: {{ .Values.clusterSize | default 1 | int }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      coherenceDeployment: {{ template "coherence.fullname" . }}
      component: WebServerPod
  serviceName: {{ template "coherence.name" . }}
  template:
    metadata:
      labels:
{{- include "coherence.release_labels" . | indent 8 }}
        component: WebServerPod
      annotations:
    spec:
{{- if .Values.imagePullSecrets }}
  {{- $secretsType := typeOf .Values.imagePullSecrets }}
      imagePullSecrets:
  {{- if eq $secretsType "string" }}
      - name: {{ .Values.imagePullSecrets }}
  {{- else }}
    {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: "http-port"
              containerPort: 8080
          env:
          - name: JAVA_TOOL_OPTIONS
            value: {{ printf  "-Dcoherence.wka=%s -Dcoherence.cluster=%s" .Values.wka .Values.clusterName | quote }}
